-- Stations are the stable reference points for every route and journey.
-- The station code (e.g. SBC, MAS) is the business identifier; the name is display text.
CREATE TABLE stations (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(10)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    city       VARCHAR(100),
    state      VARCHAR(100),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_stations_code   UNIQUE (code),
    CONSTRAINT ck_stations_code   CHECK (code = upper(code) AND length(trim(code)) > 0),
    CONSTRAINT ck_stations_name   CHECK (length(trim(name)) > 0)
);

-- Station search is by name; the UNIQUE constraint already indexes code.
CREATE INDEX idx_stations_name ON stations (lower(name));
